include:
  - https://gitlab.com/jitesoft/gitlab-ci-lib/raw/master/container_scan-v2.yml

stages:
  - build
  - scan

build:
  stage: build
  image: registry.gitlab.com/jitesoft/dockerfiles/misc:latest
  before_script:
    - apk add --no-cache wget grep
    - VERSION=$(wget -qO- https://github.com/keybase/client/releases | grep -oP '(?<=releases\/tag\/)(.*?)(?=\">)' | awk 'NR==1{print $1}')
  script:
    - TAGS="jitesoft/cfssl:latest ${CI_REGISTRY_IMAGE}:latest quay.io/jitesoft/cfssl:latest"
    - docker build -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} .
    - helper multitag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} ${TAGS}
    - helper multipush ${TAGS}

scan:
  extends: .container_scanning
  variables:
    SCANNING_IMAGE_NAME: "${CI_REGISTRY_IMAGE}:latest"
