include:
  - https://gitlab.com/jitesoft/gitlab-ci-lib/raw/master/container_scan-v2.yml

variables:
  PLATFORMS: "linux/amd64,linux/arm64"

stages:
  - build
  - scan

build:
  stage: build
  image: registry.gitlab.com/jitesoft/dockerfiles/misc:latest
  script:
    - HASH=$(wget -qO- https://github.com/cloudflare/cfssl | tr -d '\n' | tr -d ' ' | grep -oP '(?<=commit-tease-sha).*[>]([\da-f]+)(?=<)' | grep -oP '(?<=\>)([\da-f]+)' | awk 'NR==1{print $1}')
    - TAG_LIST=$(helper "jitesoft/cfssl,${CI_REGISTRY_IMAGE}", "latest,${HASH}")
    - docker buildx build --platform ${PLATFORMS} --progress plain --push ${TAG_LIST} .
    - docker pull ${CI_REGISTRY_IMAGE}:latest
    - docker tag ${CI_REGISTRY_IMAGE}:latest quay.io/jitesoft/cfssl:latest
    - docker tag ${CI_REGISTRY_IMAGE}:latest quay.io/jitesoft/cfssl:${HASH}
    - docker push quay.io/jitesoft/cfssl:latest
    - docker push  quay.io/jitesoft/cfssl:${HASH}
  tags:
    - buildx
    - jitesoft
    - protected

scan:
  extends: .container_scanning
  variables:
    SCANNING_IMAGE_NAME: "${CI_REGISTRY_IMAGE}:latest"
